return {}
-- return {
--     "folke/trouble.nvim",
--     opts = {}, -- for default options, refer to the configuration section for custom setup.
--     cmd = "Trouble",
--     config = function()
--         require("trouble").setup({
--             -- your configuration comes here
--             -- or leave it empty to use the default settings
--             -- refer to the configuration section below
--         })
--     end,
--     keys = {
--         -- next quickfix list
--         {
--             "<leader>xn",
--             "<cmd>Trouble quickfix next<cr>",
--             desc = "Next Quickfix List (Trouble)",
--         },
--         {
--             "<leader>xp",
--             "<cmd>Trouble quickfix prev<cr>",
--             desc = "Previous Quickfix List (Trouble)",
--         },
--         {
--             "<leader>xx",
--             "<cmd>Trouble diagnostics toggle<cr>",
--             desc = "Diagnostics (Trouble)",
--         },
--         {
--             "<leader>xX",
--             "<cmd>Trouble diagnostics toggle filter.buf=0<cr>",
--             desc = "Buffer Diagnostics (Trouble)",
--         },
--         {
--             "<leader>cs",
--             "<cmd>Trouble symbols toggle focus=false<cr>",
--             desc = "Symbols (Trouble)",
--         },
--         {
--             "<leader>cl",
--             "<cmd>Trouble lsp toggle focus=false win.position=right<cr>",
--             desc = "LSP Definitions / references / ... (Trouble)",
--         },
--         {
--             "<leader>xL",
--             "<cmd>Trouble loclist toggle<cr>",
--             desc = "Location List (Trouble)",
--         },
--         {
--             "<leader>xQ",
--             "<cmd>Trouble qflist toggle<cr>",
--             desc = "Quickfix List (Trouble)",
--         },
--     },
-- }
